aruco_tracking:
  process_freq: 10.0
  
  # flag
  is_eval: false
  compare_mode: false

  # threshold
  marker_cnt_th: 25 # count for fixing target when multi marker detected
  filter_buf_size: 10 # moving average filter buff size
  noise_dist_th_m: 3.0
  noise_cnt_th: 6 # (3/5)*process_frequency

  # aruco marker
  dictionaryID: 0
  big_marker_id: 0
  small_marker_id: 1
  big_marker_size_m: 0.2
  small_marker_size_m: 0.06
  
usb_cam:
  video_device: '/dev/video0'
  brightness: 200
  contrast: 20
  saturation: 100
  sharpness: 40

  pixel_format: 'yuyv'

  autofocus: false
  focus: 51

  io_method: 'mmap'
  image_width: 640
  image_height: 480
  framerate: 10

  autoexposure: false
  exposure: 100
  gain: 10

  auto_white_balance: false
  white_balance: -1

  camera_frame_id: 'camera_link'
  camera_name: 'usb_cam'