usb_cam:
  video_device: '/dev/video0'
  # brightness: 100
  # contrast: 0
  # saturation: 50
  # sharpness: 40
  # hue: 40

  pixel_format: 'mjpeg'
  # pixel_format: 'yuyv'

  autofocus: false
  focus: -1

  io_method: 'mmap'
  # image_width: 1920
  # image_height: 1080
  # image_width: 1280
  # image_height: 720
  image_width: 640
  image_height: 480

  framerate: 30

  autoexposure: true
  exposure: 100
  gain: -1 

  auto_white_balance: true
  white_balance: -1

  camera_frame_id: 'camera_link'
