data_ns: '/kuam/data'
maneuver_ns: '/kuam/maneuver'
visual_ns: '/kuam/visual'

kuam:
  data:
    aruco_tracking:
      process_freq: 10.0
      
      # flag
      compare_mode: false

      # threshold
      marker_cnt_th: 25 # count for fixing target when multi marker detected
      filter_buf_size: 10 # moving average filter buff size
      noise_dist_th_m: 3.0
      noise_cnt_th: 3 # (3/10)*process_frequency

      # aruco marker
      dictionaryID: 0
      small_marker_ids: [9, 10, 11, 12]
      small_marker_size_m: 0.04
      medium_marker_ids: [4, 5, 6, 7, 8]
      medium_marker_size_m: 0.06
      big_marker_ids: [0, 1, 2, 3]
      big_marker_size_m: 0.2

    usb_cam:
      video_device: '/dev/video0'
      brightness: 100
      contrast: 100
      saturation: 100
      sharpness: 10

      pixel_format: 'yuyv'

      autofocus: false
      focus: -1

      io_method: 'mmap'
      image_width: 640
      image_height: 480
      framerate: 30

      autoexposure: true
      exposure: 10
      gain: -1

      auto_white_balance: true
      white_balance: -1

      camera_frame_id: 'camera_link'
      camera_name: 'usb_cam'
  
  maneuver:
    state_machine:
      process_freq: 20.0

      # takeoff
      takeoff_alt_m: 3.0
      reached_dist_th_m: 0.7 # checking have reached to mission destination waypoint
      guidance_dist_th_m: 0.7 # checking have reached to next waypoint during flight mode

      # landing
      landing_threshold_m: 0.2 # for distingush kuam control and px4 control during landing 
      landing_standby_alt_m: 3.0 # waiting for detecting marker during landing state
      standby_dist_th_m: 1.5 # checking have reached to landing standby waypoint during landing state
      maf_buf_size: 20 # Moving average filter apply to average pose of 
      big_target_mapping: 0.25
      medium_target_mapping: 0.2
      small_target_mapping: 0.1257

      # flight
      alt_offset_m: 23.156

      # emerg
      battery_th_per: 0.10

    tf_broadcaster:
      process_freq: 50.0
      
      # flag
      is_finding_home: false

      exp_camera_height_m: 1.5
      
      extrinsic_imu_to_camera_x: 0.0
      extrinsic_imu_to_camera_y: 0.0
      extrinsic_imu_to_camera_z: 0.0
      
    mission_manager:
      process_freq: 30.0
    
