data_ns: '/kuam/data'
maneuver_ns: '/kuam/maneuver'
visual_ns: '/kuam/visual'

kuam:
  maneuver:
    state_machine:
      process_freq: 20.0

      # takeoff
      takeoff_alt_m: 3.0
      reached_dist_th_m: 0.7 # checking have reached to mission destination waypoint
      guidance_dist_th_m: 0.7 # checking have reached to next waypoint during flight mode

      # landing
      landing_threshold_m: 0.2 # for distingush kuam control and px4 control during landing 
      landing_standby_alt_m: 3.0 # waiting for detecting marker during landing state
      standby_dist_th_m: 1.5 # checking have reached to landing standby waypoint during landing state
      maf_buf_size: 20 # Moving average filter apply to average pose of 
      big_target_mapping: 0.25
      medium_target_mapping: 0.2
      small_target_mapping: 0.1257

      # flight
      alt_offset_m: 23.156

      # emergy
      battery_th_per: 0.10

    tf_broadcaster:
      process_freq: 50.0
      
      # flag
      is_finding_home: false

      exp_camera_height_m: 1.5
      
      extrinsic_imu_to_camera_x: 0.0
      extrinsic_imu_to_camera_y: 0.0
      extrinsic_imu_to_camera_z: 0.0
      
    mission_manager:
      process_freq: 30.0
    
