data_ns: '/kuam/data'
maneuver_ns: '/kuam/maneuver'
visual_ns: '/kuam/visual'

kuam:
  data:
    aruco_tracking:
      process_freq: 10.0
      
      # flag
      is_eval: false
      compare_mode: false

      # threshold
      marker_cnt_th: 25
      filter_buf_size: 10
      noise_dist_th_m: 3.0
      noise_cnt_th: 6 # (3/5)*process_frequency

      # aruco marker
      dictionaryID: 0
      big_marker_id: 0
      small_marker_id: 1
      big_marker_size_m: 0.2
      small_marker_size_m: 0.06

  maneuver:
    state_machine:
      process_freq: 20.0

      # takeoff
      takeoff_alt_m: 3.0
      reached_dist_th_m: 0.4
      guidance_dist_th_m: 0.7

      # landing
      landing_threshold_m: 0.5
      landing_standby_alt_m: 3.0
      landing_duration_s: 120
      standby_dist_th_m: 1.5
      virtual_border_max_side_m: 6.0
      virtual_border_angle_0_deg: 20.0
      virtual_border_angle_1_deg: 10.0
      alt_division_m: 10.0

      # flight
      alt_offset_m: 23.156

      # emerg
      battery_th_per: 0.10

    tf_broadcaster:
      process_freq: 50.0
      
      # flag
      is_finding_home: false

      target_height_m: 20
      drone_offset_m: 0.188
      exp_camera_height_m: 1.5
      
      extrinsic_imu_to_camera_x: 0.1257
      extrinsic_imu_to_camera_y: 0.0
      extrinsic_imu_to_camera_z: 0.0
      
    mission_manager:
      process_freq: 30.0
    