mission_manager:
  process_freq: 30.0
  data_ns: '/kuam/data'

tf_broadcaster:
  process_freq: 50.0
  
  # flag
  is_finding_home: false

  exp_camera_height_m: 1.5
  
  extrinsic_imu_to_camera_x: 0.0
  extrinsic_imu_to_camera_y: 0.0
  extrinsic_imu_to_camera_z: 0.0