state_machine:
  process_freq: 20.0

  # takeoff
  takeoff_alt_m: 2.5
  reached_dist_th_m: 0.3 # checking have reached to mission destination waypoint
  guidance_dist_th_m: 2.5 # checking have reached to next waypoint during flight mode

  # landing
  landing_threshold_m: 0.5 # for distinguish kuam control and px4 control during landing 

  # emergy
  battery_th_per: 0.10

state_machine_tf:
  process_freq: 50.0
  camera_frame_id: camera_link
  is_real: true
  extrinsic_imu_to_camera_x_m: 0.0
  extrinsic_imu_to_camera_y_m: 0.0
  extrinsic_imu_to_camera_z_m: 0.0
  extrinsic_imu_to_camera_r_deg: 0.0
  extrinsic_imu_to_camera_p_deg: 180.0
  extrinsic_imu_to_camera_y_deg: 90.0

state_machine_visual:
  process_freq: 5.0

  width: 350.0
  height: 230.0
  left: 10.0
  top: 10.0